### ISSUE TITLE
Usabilidade - Melhorar

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-QueroCultura#101]
Pela página inicial, não dá pra saber para que serve a plataforma! (já comentei isso com MDS)
Primeira frase:
"Bem vindo
O QueroCultura é uma plataforma Web de visualização de dados. Vamos começar o tour !"

Essa primeira interação com o usuário deveria deixar explicito o propósito da plataforma.

**Comment by caiooliv** [comment]
Foi feita uma refatoração do tour para a melhorar a interação inicial do usuário, outras melhoras de usabilidade foram feitas na #92
