### ISSUE TITLE
TS04 -  Testar Mapa

### ISSUE THREAD

**Issue by josutk** [fga-gpp-mds/2017.2-QueroCultura#16]
Eu como desenvolvedor , desejo testar o mapa, para garantir a qualidade do código

responsáveis: @hugonxc   @m7rodrigues  @caiooliv 

Critérios de Aceitação :

- [x] Melhorar os testes já existentes
- [ ] Cobertura do teste no mapa em 90%
- [x] Configurar ferramenta de cobertura
- [ ] Criar integração com o Travis CI para execução dos testes

**Comment by cjjcastro** [comment]
Os testes de javascript do mapa foram finalizados.

**Comment by cjjcastro** [comment]
Utilizamos o framework Jasmine para escrever os testes de javascript. Para fazer a cobertura dos testes utilizamos o Karma, porém só conseguimos configurar o Karma localmente, tivemos problemas com a configuração do Docker.
