### ISSUE TITLE
TS05 - Configurar o Radon para coletar Cloc, loc e complexidade ciclomática

### ISSUE THREAD

**Issue by josutk** [fga-gpp-mds/2017.2-QueroCultura#17]
Eu como desenvolvedor desejo coletar as métricas  Cloc, loc e complexidade ciclomática para garantir a manutenibilidade do código produzido

Responsáveis: @rodrigocam @lukassxp 

Critério de Aceitação:

- [x] Coleta Cloc

- [ ] <s>Coleta Loc</s>

- [x] Coleta  Complexidade cilclomatica

**Comment by rodrigocam** [comment]
O Radon não calcula CLOC e LOC, atualmente verificando outra maneira de coleta.

**Comment by rodrigocam** [comment]
A métrica LOC é a mesma CLOC, porém, no plano de medição consta como "LOC por método" (AMLOC). Não existem ferramentas (oficiais, vide diguinalizo) que coletem tal métrica em Python. Temos duas opções: **Retirar a métrica** ou **Usar o diguinalizo**.

As coletas de Complexidade Ciclomática (Radon) e CLOC (CLOC) serão coletadas manualmente, fiz um guia neste documento - [](https://docs.google.com/document/d/1SZhuvWz95Y7Zyc1KcB-mWtMBjT0m20izD86RlkNaiWE)

**Comment by josutk** [comment]
Acredito que para os fins do trabalho usar o diguinalizo não seria bom para os fins do trabalho, acho a melhor atitude é retirar o loc

**Comment by rodrigocam** [comment]
Também não acho o diguinalizo uma boa opção, melhor removermos a métrica.
