### ISSUE TITLE
TS03 - Pegar a cobertura de todo o código 

### ISSUE THREAD

**Issue by josutk** [fga-gpp-mds/2017.2-QueroCultura#18]
Eu como desenvolvedor, desejo garantir que a cobertura de teste alcance todo o código

responsaveis : @pablodiegoss  @IgorVeludo 

Critérios de Aceitação : 

Pegar a cobertura de testes de todo o código que não está sendo contabilizado na cobertura

**Comment by pablodiegoss** [comment]
Foi realizada a substituição da ferramenta de coleta da cobertura no Docker e Travis.
Assim, é possível verificar através do log do Travis a cobertura de cada arquivo individualmente, e também na página do Coveralls.
Caso queira verificar localmente a cobertura de testes identificando cada arquivo e como melhora-los, utilize os comandos:

sudo docker-compose run web bash
py.test --cov-report html --cov=.

será gerada então uma pasta contendo arquivos .html chamada HTMLCov, exibindo em cada um deles as linhas que estão cobertas por testes e as que não estão de cada arquivo .py do projeto.
