### ISSUE TITLE
TS02 - Refatorar interface do Mapa

### ISSUE THREAD

**Issue by hugonxc** [fga-gpp-mds/2017.2-QueroCultura#19]
Eu como desenvolvedor, desejo refatorar as requisições para melhor manutenibilidade do código.

responsaveis : @cjjcastro, @Jefersonalves

- [ ] Ajustar paleta de cor responsiva(day/night)
- [x] Estabelecer web tour no primeiro acesso
- [x] Remover bugs na navegação no mapa

**Comment by Jefersonalves** [comment]
Ponderamos ser melhor usar apenas uma forma de visualização e não usar day/night
