### ISSUE TITLE
US01 - Mapa Multi-instância

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#23]
Eu como cidadão, desejo visualizar edições que acontecem em várias instâncias do mapas culturais.

Responsáveis: @Jefersonalves, @lukassxp 

Critérios de Aceitação:

- [x] Visualização de pelomenos da base nacional, de São paulo e Ceará
- [ ] Verificar se existe duplicidade entre pontos

**Comment by lukassxp** [comment]
Visualização de atualizações nas instâncias de SP e CE funcionando, ainda necessita refatoração do código para evitar repetição. Estou também avaliando a melhor forma de evitar a duplicidade de registros.

**Comment by lukassxp** [comment]
Durante a reunião de planejamento da Sprint 2 ficou decidido em conjunto com o grupo que nesse momento não é necessário tratar duplicidade de pontos, pois a idéia da duplicidade que tinhamos antes da implementação da issue foi alterada.
