### ISSUE TITLE
US02 - Filtros para Visualização de marcadores

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#24]
Eu como cidadão, desejo ter filtros para visualizar edições de uma categoria específica de marcador.

Responsáveis: @cjjcastro @rodrigocam 

Critérios de aceitação:
 - [x] Exibir por tipo de marcador
 - [ ] Especificar horário de atualização nos marcadores
 - [x] Multiplos filtros ao mesmo tempo
 - [ ] Filtro de tempo de atualização

**Comment by rodrigocam** [comment]
Não vimos a necessidade dos filtros de horário, o cliente especificou isso? Qual o valor desta funcionalidade no projeto, tendo em vista que o mapa já exibe os marcadores das últimas 24 horas (estático) e os da última hora (piscando)?

**Comment by rodrigocam** [comment]
Adicionamos além destas funcionalidades, uma opção de deixar o mapa branco e preto, de acordo com a opção do usuário.

**Comment by pablodiegoss** [comment]
O filtro de Horário foi uma sugestão do professor Maurício durante a release 1 que se encaixou na história atual, não necessariamente feita pelo cliente, mas com esta última atualização de marcadores do dia e da ultima hora talvez não seja mais tão relevante.
