### ISSUE TITLE
US04 - Tour do Site

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#26]
Eu como cidadão, desejo ter um tour com mais dinamicidade, que não seja apenas um botão de next, mas indique os botões e funcionalidades.

Responsáveis: @caiooliv, @m7rodrigues 

Critérios de aceitação:
 - [ ] As funcionalidades devem executadas durante o tour
 - [ ] Pouco texto e mais imagens e indicações.

**Comment by caiooliv** [comment]
As funcionalidades recebem foco durando o tour como o especificado , porém a funcionalidade de "markers" não recebe o foco.
