### ISSUE TITLE
Externalizar em YAML definição das instâncias fonte

### ISSUE THREAD

**Issue by nitaibezerra** [fga-gpp-mds/2017.2-QueroCultura#29]
Criar um arquivo YAML para facilitar a inclusão de URLs de mais instâncias de Mapas Culturais

**Comment by lukassxp** [comment]
O arquivo YAML foi adicionado ao projeto e atualmente os indicadores de Museus, Eventos e Projetos fazem uso dele para requisitar dados a API Mapas Culturais. Está também em curso uma refatoração nos indicadores de Agentes para que ele se encaixe no novo padrão de back-end e faça uso do YAML em suas requisições.
