### ISSUE TITLE
US06 - Extrair Indicadores Culturais de Agentes [Backend]

### ISSUE THREAD

**Issue by rodrigocam** [fga-gpp-mds/2017.2-QueroCultura#31]
Eu como usuário desejo visualizar indicadores culturais sobre os agentes cadastrados na plataforma dos mapas culturais e suas instâncias.

- [x] Os indicadores criados não devem ser globais (comparativos entre instâncias)
- [x] A implementação (de pelo menos um indicador) deve abranger todos os níveis da arquitetura
- [x] Utilizar dados diversos (tags, descrição, área, gênero do agente, etc)

**Comment by lukassxp** [comment]
O código python foi feito visando extrair dados apenas da instância principal da plataforma Mapas Culturais, ficou decidido na sprint review a melhor forma de transformar nossa aplicação em uma aplicação multi-instância. O celery que é encarregado de atualizar os indicadores periodicamente está funcionando, porém necessita de uma atualização em suas configurações para que faça uma atualização assim que o projeto é executado.
