### ISSUE TITLE
US07 - Integração com o Jenkins

### ISSUE THREAD

**Issue by rodrigocam** [fga-gpp-mds/2017.2-QueroCultura#32]
Eu como usuário desejo ter a aplicação com deploy contínuo utilizando a ferramenta Jenkins, para permitir o acesso a aplicação via servidores do Ministério de Cultura.

- [ ] A aplicação deve estar sendo continuamente publicada nos servidores do MinC

**Comment by pablodiegoss** [comment]
A integração foi realizada juntamente com membros do MinC, porém, a máquina ainda não responde a acessos externos, tendo apenas um IP local no servidor. Aguardamos configuração do DNS para redirecionamento da url.

**Comment by pablodiegoss** [comment]
O deploy não é automático utilizando a integração com o Github do Jenkins, mas feita de forma manual pelo pessoal do MinC, porém, tudo está configurado e rodando no link [Quero Cultura](http://querocultura.lab.cultura.gov.br).

**Comment by RochaCarla** [comment]
Coloca esse link na wiki de vcs (parece que esse é o link de produção/homolog de vcs). O que está na wiki está bastante desatualizado (estão fazendo deploy contínuo?)
