### ISSUE TITLE
Remover Copyright da solução

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#36]
Estudar e substituir o copyright por Copyleft ou similar na página principal do mapa.

**Comment by josutk** [comment]
Foi realizado a elaboração do seguinte documento https://github.com/fga-gpp-mds/2017.2-QueroCultura/wiki/Copyleft, para torna visível o que é copyleft aos membros do projeto e fazendo apontamento da licença GPL, para o uso do copyleft nesse projeto.
