### ISSUE TITLE
Marcadores que param de piscar no Mapa

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#37]
Alguns marcadores recentes (no prazo de 1 hora, que deveriam estar piscando) parecem parar de piscar após alguns segundos na tela. É necessário conferir os dados recebidos pela aplicação e os dados na API pra garantir que isso não é um bug e são apenas marcadores que passaram de 1h desde sua edição.

**Comment by josutk** [comment]
O problema foi corrigido alterando a ordem de precedência entre as imagens .gif e .png, antes as imagens png ficavam por cima das imagens gif, parecendo assim que o mapa não piscava!
