### ISSUE TITLE
Melhorar Trava de tela no Mapa

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#38]
A trava de tela do mapa está atrapalhando a utilização pelo usuário, onde, por exemplo, caso o zoom esteja suficiente para visualizar o país completamente, não é possível centralizar a tela em São Paulo, sendo sempre resetado para uma posição centralizada no país todo.
A trava não está permitindo estas movimentações dentro do próprio país com o zoom diminuído.

**Comment by nitaibezerra** [comment]
Tem a ver com https://github.com/fga-gpp-mds/2017.2-QueroCultura/issues/72

**Comment by cjjcastro** [comment]
A trava de tela do mapa já não atrapalha mais, agora é possível centralizar em qualquer estado brasileiro com o zoom mínimo, sendo possível visualizar o país completamente.
