### ISSUE TITLE
US14- Relacionar o Link dos marcadores com suas respectivas Instâncias

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#39]
Atualmente os links dos marcadores redirecionam para a página das APIs gerais. Um marcador de projeto que foi obtido através do MapasCulturais central, irá ser referenciado sempre para o site mapas.cultura.gov.br e não para sua instância onde foi cadastrado.
Utilizando informações da API de um marcador é possível redirecionar para a instância específica onde este marcador foi criado, tendo então por exemplo: 
ao invés de: http://mapas.cultura.gov.br/agente/24346/
o link: http://laguna.sc.mapas.cultura.gov.br/agente/24346/

**Comment by pablodiegoss** [comment]
Todas as informações de Instâncias podem ser encontrados neste link da API, sendo então possível relacionar o ID de Subsite de um Agente com o ID deste link abaixo para encontrar qual marcador pertence a qual instância.
http://mapas.cultura.gov.br/api/subsite/find?@select=*

**Comment by josutk** [comment]
Navegando pela aplicação e fazendo alguns teste para ver o problema relatado eu entendi que o link é redirecionado para a instancia de criação, fazendo o que foi feito:
criei um agente no mapas de são paulo, ao abrir o link do agente redirecionou para a instancia de são paulo dos mapas culturais,  então acredito que a aplicação redireciona o link de acordo com a instancia de criação, um segundo teste foi realizado criando agentes nos mapas culturais geral e no mapas culturais de são paulo e foi observado o seguinte, que quando cria um agente na instancia de são paulo ele não aparece na instancia geral, e quando se cria pela instancia geral um agente em são paulo e não aparece na instancia de são paulo, gostaria de mais informações sobre essa issue para ver como agir.
