### ISSUE TITLE
Identificação de atualizações do Feed

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#40]
O feed está identificando marcadores através do ID, porém, os ID's se repetem entre instâncias não conectadas: São Paulo, Mapa nas Nuvens...
A identificação deve ser feita utilizando mais critérios do que apenas o ID para evitar que atualizações novas não sejam exibidas por terem o mesmo ID que outro marcador que já está sendo exibido.

**Comment by josutk** [comment]
A nova forma de identificar é feita da seguinte forma, usa primeiro a sigla da respectiva instancia concatenado com o valor do id.
exemplo: para o agente http://spcultura.prefeitura.sp.gov.br/agente/29461/
o seu id seria: sp29461
