### ISSUE TITLE
US08 - Visualizar indicadores de agentes

### ISSUE THREAD

**Issue by Jefersonalves** [fga-gpp-mds/2017.2-QueroCultura#41]
* [ ] Consumir dados gerados e/ou manipulados em #31 e gerar visualização gráfica

**Comment by m7rodrigues** [comment]
Os indicadores de agentes é exibido na página de agentes, contendo quatro gráficos, são eles: Quantidade de registros cadastrados por mês, porcentagem de agentes, quantidade de agentes por área de atuação e crescimento da plataforma em relação aos cadastros realizados.
