### ISSUE TITLE
US09 - Extrair Indicadores Culturais de Eventos [Backend]

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#47]
Eu como sistema desejo criar indicadores culturais sobre os eventos cadastrados na plataforma dos mapas culturais e suas **instâncias**.

- [x] Os indicadores criados não devem ser globais (comparativos entre instâncias)
- [x] Os indicadores devem englobar os dados de todas as instâncias.
- [x] #29

**Comment by lukassxp** [comment]
A issue foi finalizada com sucesso, não identificamos debitos, estamos aguardando revisão dos demais membros do projeto. Os indicadores gerados pegam dados de todas as instâncias da plataforma Mapas Culturais que estão descritas no arquivo yaml. Os dados provenientes das consultas em multi-instâncias são somados com a intenção de não gerar indicadores comparativos. O arquivo yaml foi implementado primeiramente pela US10 e posteriormente alterado por nós.
