### ISSUE TITLE
US10 - Extrair Indicadores culturais de Bibliotecas [Backend]

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#48]
Eu como sistema desejo criar indicadores culturais sobre as bibliotecas cadastradas na plataforma dos mapas culturais e suas **instâncias**.

- [x] Os indicadores criados não devem ser globais (comparativos entre instâncias)
- [x] Os indicadores devem englobar os dados de todas as instâncias.
- [x] #29

**Comment by josutk** [comment]
Foi criado todos os indicadores seguindo as especificações da planilha de consolidação de ideias,
O Arquivo yaml, foi feito colocando todas as urls nele e fazendo uso da biblioteca yaml do python pra ler e recuperar essas urls.
