### ISSUE TITLE
US12 - Visualizar indicadores culturais de bibliotecas [Frontend]

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#50]
Eu como usuário, desejo visualizar gráficos que apresentem os dados dos indicadores de bibliotecas da plataforma.

 - [x] Os gráficos não podem ser poluídos demais.
 - [x] Legendas e textos que expliquem a origem do indicador
 - [x] 80% de cobertura nos testes

**Comment by cjjcastro** [comment]
O desenvolvimento desta aplicação consistiu na criação dos gráficos utilizando os dados disponibilizados pelo Backend. Foram criados os gráfico utilizando funções criadas no app quero_cultura.
Foi refatorado o layout, modificando o base.html, e também foi modificado o css dos apps de biblioteca, agentes e eventos.
