### ISSUE TITLE
TS30 - Ambiente para execução dos testes javascript

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#52]
Eu como desenvolvedor, desejo executar os testes de Javascript da aplicação em ambiente preparado. 
- [x] Container Node com a ferramenta Karma ou semelhante.
- [x] Obter a cobertura de testes do javascript.

**Comment by Jefersonalves** [comment]
Serviço para testes criado. Foi usando um outro arquivo yml para o  docker compose, com o objetivo de evitar que este seja executado em produção. 

Para obter a cobertura dos arquivos js siga os passos:
1. Execute o serviço do karma: `docker-compose -f docker-compose.testjs.yml up`
Isto irá executar todos os testes javascript criados com o `Jasmine`
2. Acesse o arquivo html para visualizar a cobertura
`/coverage/PhantomJS 2.1.1 (Linux 0.0.0)/lcov-report/index.html`
