### ISSUE TITLE
Alterar o layout do feed de atualizações

### ISSUE THREAD

**Issue by rodrigocam** [fga-gpp-mds/2017.2-QueroCultura#57]
- [x] Deixar responsivo
- [x] Deixar mais bonito

**Comment by pablodiegoss** [comment]
- [ ] O feed deve exibir a Hora da modificação para evidenciar a instantaneidade da informação
- [ ] Substituir as bolas coloridas pelos ícones da plataforma de cada categoria

**Comment by rodrigocam** [comment]
- [ ] #74
