### ISSUE TITLE
Dar zoom no mapa ao clicar em uma atualização no feed

### ISSUE THREAD

**Issue by rodrigocam** [fga-gpp-mds/2017.2-QueroCultura#58]
Eu como usuário, desejo poder saber a localização de uma atualização que surgiu no feed, de forma que clicando sobre ela, o mapa guie para a localização ou indique de alguma forma onde está aquela nova atualização.

- [x] Movimentação do mapa ou indicação visual para o ponto clicado no feed

**Comment by cjjcastro** [comment]
Já é possível visualizar o marcador ao clicar em uma atualização no feed.
