### ISSUE TITLE
Feedback - melhorias

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2017.2-QueroCultura#62]
Tem boas evidencias da aplicação da metodologia ágil. A organização das issues está ótima! Algumas melhorias são sugeridas

- [x] Melhorar a distribuição dos commits. Está bastante desnivelado. Alguns membros não tem commits na R2, e há grande discrepância entre os comitters. Faz parte das práticas ágeis garantir que a equipe possa ser auto-organizável. Se não há nivelamento de conhecimento técnico, nem das habilidades/competências necessárias para execução da metodologia, o auto-gerenciamento/auto-organização não é possível 

- [x] Melhorar a comunicação nas issues e nos pull-request. A comunicação deve ser concentrada no próprio repositório para evidenciar troca de conhecimento, e evidenciar as análises feitas. Essa prática ágil e de comunidades de software livre deve ser exercitada no projeto.

- [x] O repositório atende a maioria das recomendações de software livre. Porém, vale refatorar o README e verificar as demais recomendações. Checklist:
https://github.com/fga-gpp-mds/2017.2-QueroCultura/community
https://opensource.guide/starting-a-project/

- [x] A wiki está bem desatualizada. Falta incluir as  métricas de código, outros indicadores e fazer a análise dos indicadores e métricas referentes a uma sprint. A atualização dá transparência ao ciclo de vida de projeto, além de facilitar a tomada de decisão (uma vez que todos os indicadores e métricas podem ser analisados de uma só vez)

- [x] Falta o roadmap da R2

- [x] Gere pré releases ao final de cada sprint. Registre quais foram as histórias/features entregues, quais os bugs e pontos de melhorias encontradas. Além de ser um resumo da sprint, dá transparência às entregas.

**Comment by Jefersonalves** [comment]
A equipe conseguiu ao longo do tempo encorporar as melhorias sugeridas
