### ISSUE TITLE
Corrigir requisições de dados de agentes

### ISSUE THREAD

**Issue by caiooliv** [fga-gpp-mds/2017.2-QueroCultura#66]
- [x] Usar arquivo YAML para fazer requisições multi-instância.

**Comment by lukassxp** [comment]
Ocorreu um problema inesperado na requisição de dados de agentes da instância de São Paulo da plataforma Mapas Culturais. Estamos buscando uma forma de resolver este imprevisto.

**Comment by pablodiegoss** [comment]
Os dados requisitados para agentes de São Paulo causam um erro de alocação de muita memória, talvez os dados sejam maiores que o cache disponível para alocação no container ou manipulação do Django.
