### ISSUE TITLE
US15 - Indicadores de Projeto

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#68]
Eu como usuário, desejo visualizar indicadores para os dados de Projetos da plataforma mapas culturais.

- [x] Utilizar o arquivo YAML pra obter os links para as APIs
- [x] Deve-se utilizar os métodos do ChartJS do app quero_cultura para exibir os gráficos e dados
- [ ] Os dados exibidos devem estar ordenados, filtrados e de forma sucinta.

**Comment by lukassxp** [comment]
Na implementação da issue definimos um novo padrão de backend para aplicação que deverá ser seguido em todos os indicadores multi-instância do projeto, definimos também alguns metódos para geração de indicadores que deverão ser seguidos até por indicadores que não se encaixam no padrão multi-instância. Foram desenvolvidos gráficos para todos os indicadores de projetos, utilizamos o padrão adotado nos outros indicadores previamente implementados. Está em discussão a adoção de um novo framework para o front-end, no entanto com o intuito de finalizar a issue realizamos a implementação completa no padrão atual do projeto.
