### ISSUE TITLE
TS 21 - Incluir cache no carregamento do Mapa de atividades

### ISSUE THREAD

**Issue by nitaibezerra** [fga-gpp-mds/2017.2-QueroCultura#72]
O carregamento do mapa dispara consultas para API de todas as instâncias listadas como fontes dos dados, isso se tornará um problema enorme com a popularidade da ferramenta. A solução é fazer cache no servidor e enviar o pacote de dados consolidado para o App.

**Comment by nitaibezerra** [comment]
Vejo isso como mais um microserviço isolado dos demais. Um exemplo é a a API do SALIC que roda um cache Varnish na frente configurado para manter a resposta por 4 min

**Comment by pablodiegoss** [comment]
Buscaremos solucionar estas requisições utilizando inicialmente Redis/Celery pela maior familiaridade da equipe com a tecnologia e o curto tempo restante de projeto.

**Comment by rodrigocam** [comment]
A solução atual tornou a utilização do Celery dispensável, tendo em vista que agora as requisições são feitas por demanda.

Atualmente existem três métodos que retornam marcadores, um para resgatar marcadores do último dia, um para os da última hora e um para os últimos 3 minutos. Cada um desses métodos executa uma verificação no banco de dados antes de fazer as requisições para as API's, além disso armazenam a data da última requisição executada, assim podemos conferir se a última requisição é muito antiga e fazer uma nova no futuro.
