### ISSUE TITLE
Incluir mais infos na timeline

### ISSUE THREAD

**Issue by nitaibezerra** [fga-gpp-mds/2017.2-QueroCultura#74]
![captura de tela de 2017-11-03 23-10-05](https://user-images.githubusercontent.com/1244443/32400872-0f315122-c0ed-11e7-833f-80f987d58e06.png)

Incluir: 
* [x] cidade/UF
* [x] Horário do fato
* [x] O que aconteceu (ex. Evento criado, Agente atualizado, etc..)

**Comment by nitaibezerra** [comment]
Opa! Vale uma reflexão sobre outras infos que podem aparecer

**Comment by pablodiegoss** [comment]
A time line foi atualizada com estas informações.

![image](https://user-images.githubusercontent.com/8556291/32494941-c8bda57c-c3aa-11e7-90b5-950e5e0bc5bd.png)

Ocasionalmente alguns usuários não possuem localização, ou o endereço não "pertence" a uma cidade específica, então fica vazio o espaço de cidade, de estado ou de ambos.
