### ISSUE TITLE
US18 - Desenvolver indicadores de Espaço na plataforma Metabase

### ISSUE THREAD

**Issue by nitaibezerra** [fga-gpp-mds/2017.2-QueroCultura#75]
Esta issue é uma sugestão de mudança arquitetural para utilização da plataforma Metabase para produção dos paineis de indicadores. O Metabse é um software livre, ao estilo BI para produção de visualizações dinâmicas, que possibilita a construção de gráficos de maneira visual e componentizada. 

No caso ele pode ser conectado diretamente ao MongoDB para geração dinâmica das visualizações.

No MinC estamos experimentando o Metabase há algumas semanas. Temos uma instância em http://metabase.lab.cultura.gov.br/
Um exemplo de uso simples é este painel que conheci ontem: https://meta.mostre.me/public/dashboard/af26d09e-2994-4e39-8593-49e8a87fe5f5

Na perspectiva acadêmica, vale essa empreitada.

**Comment by lukassxp** [comment]
A issue foi concluída com sucesso. O contêiner metabase foi adicionado ao docker projeto, para o correto funcionamento do metabase no contexto da nossa aplicação também foram adicionados os contêineres postgres e docker, o primeiro com o intuito de substituir o BD interno default do metabase para possibilitar gerar um dump do banco de dados interno do metabase para que todos os desenvolvedores tenham acesso as modificações feitas nas questions e dashboards do projeto, o segundo foi adicionado visando fazer automação de algumas tarefas junto ao comando up do docker-compose. Sempre que algum desenvolvedor alterar questions ou dashboards do metabase deve ser gerado um dump do banco de dados interno do metabase seguindo os comandos listados no arquivo commands.txt que fica dentro da pasta postgres_metabase na raiz do projeto. Os testes que envolvem requisições a API MapasCulturais foram feitos utilizando mock para evitar sobrecarga nos servidores do MinC e das instâncias descentralizadas. Para subir o projeto deve ser usador sempre o comando docker-compose up e sempre que a execução do projeto for suspensa deve se usado o comando docker-compose down em sequencia.
