### ISSUE TITLE
US20 - Criar Documentação para o BD e sua Arquitetura

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#83]
Eu como usuário desejo uma documentação detalhada da arquitetura do banco, sua utilização e funcionamento na aplicação para que seja possível continuar o trabalho futuramente com manutenções, evoluções e possíveis integrações com as outras aplicações do MinC.

**Comment by josutk** [comment]
Para a aceitação dessa historia deverão ser especificados os seguintes topicos:

- [ ]  Django ORM 
- [ ] Funcionamento MongoEngine
- [ ] Funcionamento do MongoDB
- [ ]  Fluxo de trabalho do Django para o armazenamento do Django 
- [ ] Arquitetura Django (Model)

**Comment by caiooliv** [comment]
Com a refatoração da arquitetura foi necessário atualizar o documento, que pode ser encontrado no link a seguir [Documento de Arquitetura do Banco de Dados](https://github.com/fga-gpp-mds/2017.2-QueroCultura/wiki/Documento-de-Arquitetura-do-Banco-de-Dados)
