### ISSUE TITLE
US23 - Incluir endereço das outras instâncias rodando Mapas Culturais

### ISSUE THREAD

**Issue by nitaibezerra** [fga-gpp-mds/2017.2-QueroCultura#84]
Segue abaixo a lista das demais instâncias:
* http://culturaz.santoandre.sp.gov.br
* http://mapa.cultura.df.gov.br
* https://mapas.mt.gov.br
* http://estadodacultura.sp.gov.br
* http://lugaresdacultura.org.br
* http://blumenaumaiscultura.com.br
* http://jpcultura.joaopessoa.pb.gov.br
* http://mapaculturalbh.pbh.gov.br
* http://mapacultural.ubatuba.sp.gov.br
* http://londrinacultura.londrina.pr.gov.br
* http://www.mapacultural.pe.gov.br

ps. lembro destas até agora

**Comment by nitaibezerra** [comment]
Adicionei Pernambuco (http://www.mapacultural.pe.gov.br/) ali na lista

**Comment by cjjcastro** [comment]
Todos os endereços foram acrescentados, com exceção do http://mapacultural.ubatuba.sp.gov.br/ que parece está fora do ar, e o http://mapa.cultura.df.gov.br que não tem o updateTimestamp dificultando o padrão utilizado para as requisições.
