### ISSUE TITLE
US 24 - Refatorar página de indicadores

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#86]
Eu como usuário, desejo uma prévisualização dos indicadores e gráficos antes de escolher algo específico para visualizar.

- [x] Semelhante a página de informações da [Block Chain](https://blockchain.info/charts)
- [x] Utilizar como exemplo os indicadores de Espaço que já estão implementados utilizando metabase
- [x] Todas as páginas de indicadores devem seguir este novo modelo, evitando repetição de código.
- [x] Linkar os gráficos utilizando a URL da página: querocultura.lab.gov.br/space_indicators/graphic_1

Caso os gráficos do ChartJS não se adaptem a nova proposta de layout, podem ser removidos pois estão sendo construidos no metabase por outro pareamento.

**Comment by Jefersonalves** [comment]
Refatoramos o backend de forma que inserir novos gráficos ficou muito simples e o código reutilizável. Usamos como exemplo os indicadores de espaços, como sugerido

**Comment by caiooliv** [comment]
Página de indicadores refatorada com adição de dados vindo do metabase, páginas de gráficos utilizam a url da página.
