### ISSUE TITLE
US25 - Gráficos complexos do metabase

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#90]
Eu como usuário, desejo gráficos mais complexos dos dados disponibilizados pelo nosso banco de dados através das APIs do Mapa Cultura. 

- [x] Gráficos de Eventos por linguagem serem quantitativos e não porcentagem
- [x] Atualizar Gráfico de Faixa etária para classificação indicativa
- [ ] Gráfico gerado por SQL que mostre o crescimento cumulativo de todas as instâncias de forma individual.
- [x] Gerar gráficos de indicadores mistos para o Metabase através de SQLs

**Comment by cjjcastro** [comment]
Devido a dificuldade em utilizar a query do MongoDB para gerar os gráficos, decidimos criar um back-end para gerar os dados necessários para fazer os gráficos de indicadores mistos.
