### ISSUE TITLE
US27 - Melhorar usabilidade da plataforma

### ISSUE THREAD

**Issue by pablodiegoss** [fga-gpp-mds/2017.2-QueroCultura#92]
Eu como usuário, desejo que realizem as melhorias propostas para a plataforma, melhorando a usabilidade da mesma

Critérios de Aceitação
- [x] #38 
- [x] #58 
- [ ] #57 
- [ ] Ser possível selecionar o intervalo de tempo das edições exibidas no mapa
- [ ] Responsividade da tela de gráficos
- [x] Responsividade do tour

**Comment by cjjcastro** [comment]
A trava de tela do mapa já não atrapalha mais, agora é possível centralizar em qualquer estado brasileiro com o zoom mínimo, sendo possível visualizar o país completamente.
