### ISSUE TITLE
TS28 - Aumentar a segurança das informações

### ISSUE THREAD

**Issue by Jefersonalves** [fga-gpp-mds/2017.2-QueroCultura#97]
Eu como desenvolvedor, desejo que informações de senha e variáveis de ambiente sejam ocultados e externalizados em um arquivo de configuração.

- [x] Externalizar variáveis de ambiente para aquivos .env
- [ ] Ocultar senhas e chaves

**Comment by rodrigocam** [comment]
Após pesquisas, constatamos que o problema de possuir chaves e senhas expostas é um problema de quem faz o deploy, cabe a quem for fazer o deploy modificar as senhas e chaves de acordo com a necessidade, pois como o projeto é público, se fossemos ocultar alguma senha ou chave inviabilizariamos a contribuição de outras pessoas. Sendo assim, adicionamos uma resalva no README deixando claro a importância de modificar as senhas e chaves em produção.
